apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-service-config
  namespace: feature-service
data:
  SPRING_PROFILES_ACTIVE: "production"
  SPRING_DATA_REDIS_PORT: "6379"
  SERVER_PORT: "8080"
